### ISSUE TITLE
Backend

### ISSUE THREAD

**Issue by Thendo-T** [Thendo-T/Next.JS-Dashboard#1]
Needs some back-end

**Comment by yuvrajsingh1231** [comment]
for what?👋

**Comment by yuvrajsingh1231** [comment]
can u explain with example

**Comment by Thendo-T** [comment]
this comment function Github has for example, except that when the user clicks comment, the information would appear on another website(personal website) as a new card

**Comment by yuvrajsingh1231** [comment]
So it would be like when text is updated on one side it would reflect on other side in real time

**Comment by yuvrajsingh1231** [comment]
Ok i get your comment

**Comment by Thendo-T** [comment]
yeah

**Comment by yuvrajsingh1231** [comment]
So do u have any frontend redy

**Comment by Thendo-T** [comment]
Not really, it's just a skeletal dashboard. was planning on working on it at a later date

**Comment by Thendo-T** [comment]
@yuvrajsingh1231 Okay, I'll assign this issue to you then

**Comment by yuvrajsingh1231** [comment]
I want to clarification for something would you want it to be realtime or you good with printing card (personal dashboard)on page refresh

**Comment by yuvrajsingh1231** [comment]
Bcz for realtime it requires a socket client which could be done on frontend

**Comment by yuvrajsingh1231** [comment]
Or in other sanrio i can provid API to your personal dashboard

**Comment by Thendo-T** [comment]
Real-time

**Comment by yuvrajsingh1231** [comment]
So there are multiple ways of real time connections like long polling, short polling, server sent event, websocket, and using set Timeout with fetch for reducing all these complexities (science u are using next js [a powerful framework] ) i provide u API (i checked you worked on API) and u can use SWR library on frontend its save time and lot of complexitys.

**Comment by Thendo-T** [comment]
Okay,i'm fine with that too

**Comment by yuvrajsingh1231** [comment]
One last thing do u have any database and fileserver(for image storage) in mind also if u wont planned i can tell u a solution

**Comment by Thendo-T** [comment]
I'm new to back-end so I don't know yet.
What are your suggestions?

**Comment by yuvrajsingh1231** [comment]
So we can use mongodb database its free teir sufficient for personal use and mongo db is easily compatible with node js and scinece you are hosting on vercel we use its storage for storing images

**Comment by Thendo-T** [comment]
I've heard of mongodp
Yeah,we can use those

**Comment by yuvrajsingh1231** [comment]
We can use it too

**Comment by Thendo-T** [comment]
Yeah,just text and images
